# Generated by Django 2.2.1 on 2019-06-13 08:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm1', '0006_auto_20190613_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='namelink5',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
