# Generated by Django 2.2.1 on 2019-06-13 17:39

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm1', '0007_auto_20190613_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='namelink5',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='namelink5',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=12),
            preserve_default=False,
        ),
    ]
