# Generated by Django 2.2.1 on 2019-06-13 18:11

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm1', '0008_auto_20190613_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='content11',
        ),
        migrations.AddField(
            model_name='post',
            name='content32',
            field=ckeditor.fields.RichTextField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='content42',
            field=ckeditor.fields.RichTextField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='namelink25',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=12),
            preserve_default=False,
        ),
    ]
