# Generated by Django 2.2.1 on 2019-06-13 19:56

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm1', '0009_auto_20190613_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='content11',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content32',
        ),
        migrations.RemoveField(
            model_name='post',
            name='namelink25',
        ),
    ]
