# Generated by Django 2.2.1 on 2019-06-15 05:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm1', '0010_auto_20190613_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header',
            old_name='namelink5',
            new_name='namelink55',
        ),
        migrations.AddField(
            model_name='header',
            name='content422',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='content42',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Описание'),
        ),
    ]
